<div class="modal fade" id="modalRegister" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Novo Usuário</h4>
            </div>
            <form action="#" method="post" id="formRegister">
                <div class="modal-body">
                    <label for="name">Nome: </label>
                    <input type="text" required class="form-control" id="name" placeholder="Nome do Usuário"><br>

                    <label for="email">Email: </label>
                    <input type="email" required class="form-control" id="email" placeholder="Email do Usuário"><br>

                    <label for="password">Senha: </label>
                    <input type="password" required class="form-control" id="password" placeholder="Senha do Usuário"><br>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    <button class="btn btn-primary">Pronto, inserir.</button>
                </div>
            </form>
        </div>
    </div>
</div>