<div class="modal fade" id="modalUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Editar Usuário</h4>
            </div>
            <form action="#" method="post" id="formUpdate">
                <div class="modal-body">
                    <label for="nameToUpdate">Nome: </label>
                    <input type="text" required class="form-control" id="nameToUpdate" placeholder="Nome do Usuário"><br>

                    <label for="emailToUpdate">Email: </label>
                    <input type="email" required class="form-control" id="emailToUpdate" placeholder="Email do Usuário"><br>

                    <label for="passwordToUpdate">Senha: </label>
                    <input type="password" class="form-control" id="passwordToUpdate" placeholder="Senha do Usuário"><br>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    <button class="btn btn-primary">Atualizar.</button>
                </div>
            </form>
        </div>
    </div>
</div>