<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong class="panel-title">Lista de Usuários</strong>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Perfil</th>
                            <th>Atualizado em</th>
                            <th>Registrado em</th>
                            <th>Ações</th>
                        </tr>
                    </thead>

                    <tbody id="table-user">

                    </tbody>
                </table>

                <div class="text-right">
                    <button data-toggle="modal" data-target="#modalRegister" class="btn btn-info">
                        <span class="glyphicon glyphicon-plus-sign"></span>
                        Novo Usuário
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Register -->
<?=$this->partial('partials/modal-add-user');?>

<!-- Modal Update -->
<?=$this->partial('partials/modal-update-user')?>

<!-- Modal Delete -->
<?=$this->partial('partials/modal-remove-user');?>

<script>
    $(document).ready( function () {
        loadUsers();

        function loadUsers() {
            $('#table-user').html('');
            $.ajax({
                url: '/api/user',
                type: 'get',
                dataType: 'json',
                success: function (result) {
                    $.each(result.data, function (index, value) {
                        var profile = value.role == 2?'Admin':'Padrão';

                        $('#table-user').append(
                            '<tr>' +
                            '<td>' + value.name + '</td>' +
                            '<td>' + value.email + '</td>' +
                            '<td>' + profile + '</td>' +
                            '<td>' + value.updated.date + '</td>' +
                            '<td>' + value.registered.date + '</td>' +
                            '<td>' +
                                '<button data-action="update" data-id="' + value.id+ '" class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> Editar</button> '+
                                '<button data-action="delete" data-id="' + value.id+ '" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Excluir</button>'+
                            '</td>' +
                            '</tr>'
                        );
                    });
                },
                error: function (result) {
                    alert(result.message + ' | ' + result.error);
                }
            });
        }

        $('#formRegister').submit( function (event) {
            event.preventDefault();

            var userName        = $('#name').val();
            var userEmail       = $('#email').val();
            var userPassword    = $('#password').val();

            $.ajax({
                url: '/api/user',
                type: 'POST',
                dataType: 'json',
                data: {
                    name: userName,
                    email: userEmail,
                    password: userPassword
                },
                success: function (result) {
                    loadUsers();
                    $('#formRegister').trigger('reset');
                    $('#modalRegister').modal('toggle');
                    alert('Novo Usuário inserido com sucesso');
                },
                error: function (result) {
                    alert(result.message + ' | ' + result.error);
                }
            });
        });

        $('#table-user').on('click', '[data-action="delete"]', function () {
            var userId = $(this)[0].getAttribute('data-id');

            $('#modalDelete').modal('toggle');

            $('#formDelete').on('submit', function (event) {
                event.preventDefault();

                if (userId == null) {
                    return;
                }

                $.ajax({
                    url: '/api/user/' + userId,
                    type: 'DELETE',
                    dataType: 'json',
                    success: function (result) {
                        loadUsers();
                        $('#modalDelete').modal('toggle');
                        userId = null;
                        alert('Usuário excluído com sucesso');
                    },
                    error: function (result) {
                        alert(result.message + ' | ' + result.error);
                    }
                })
            });
        });

        $('#table-user').on('click', '[data-action="update"]', function () {
            var userId = $(this)[0].getAttribute('data-id');

            $('#modalUpdate').modal('toggle');

            $('#formUpdate').on('submit', function (event) {
                event.preventDefault();

                if (userId == null) {
                    return;
                }

                $.ajax({
                    url: '/api/user/' + userId,
                    type: 'DELETE',
                    dataType: 'json',
                    success: function (result) {
                        loadUsers();
                        $('#modalDelete').modal('toggle');
                        userId = null;
                        alert('Usuário excluído com sucesso');
                    },
                    error: function (result) {
                        alert(result.message + ' | ' + result.error);
                    }
                })
            });
        });
    });
</script>