<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong><span class="glyphicon glyphicon-user"></span> Autenticação</strong>
            </div>

            <div class="panel-body">
                <form action="">
                    <label for="email">Email: </label>
                    <input type="email" id="email" class="form-control input-lg" placeholder="Email"><br>

                    <label for="password">Senha: </label>
                    <input type="password" id="password" class="form-control input-lg" placeholder="Senha"><br>

                    <button class="btn btn-block btn-primary btn-lg">
                        <span class="glyphicon glyphicon-ok-sign"></span>
                        Entrar
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>